version: '3'

services:
    # client_web:
    #     build: web
    #     ports:
    #         - "8081:80"
    #     volumes:
    #         - client:/app/client
    #     depends_on:
    #         - client_mobile
    #         - server

    # client_mobile:
    #     build: mobile
    #     volumes:
    #         - client:/app/client

    server:
        build: server
        ports:
            - "8080:8080"
        environment:
            DB_HOST: database
            DB_USERNAME: root
            DB_PASSWORD: root_password
        depends_on:
            - database

    database:
        build: db
        volumes:
            - mongodb-data:/data/db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: area-db
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root_password
        restart: always

volumes:
    mongodb-data: null
    client: null
