version: '3'

services:
    client_web:
        build: web
        ports:
            - "8081:80"
        volumes:
            - client:/app/client
        depends_on:
            - client_mobile
            - server

    client_mobile:
        build: mobile
        ports:
            - "8080:8080"
        volumes:
            - client:/app/client

    server:
        build: server

    db:
        image: mongo:4.4
        volumes:
            - mongodb-data:/data/db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: ARea
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root_password
        restart: always

volumes:
    mongodb-data: null
    client: null
