version: '3'

services:
    client_web:
        build: web
        ports:
            - "8081:80"
        volumes:
            - client:/usr/share/nginx/html/assets/client
        depends_on:
            - client_mobile
            - server
        restart: always

    client_mobile:
        build: mobile
        environment:
            MOBILE_APP_FILEPATH: /app/client/area_mobile.apk
        volumes:
            - client:/app/client

    server:
        build: server
        ports:
            - "8080:8080"
            - "8180:8180"
        environment:
            DB_HOST: database
            DB_USERNAME: root
            DB_PASSWORD: AReaAvionAReactionDBPassword
        depends_on:
            - database
        restart: always

    database:
        image: mongo:4.4
        environment:
            MONGO_INITDB_DATABASE: area-db
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: AReaAvionAReactionDBPassword
        ports:
            - "27017:27017"
        volumes:
            - mongodb-data:/data/db
        restart: always

volumes:
    mongodb-data: null
    client: null
